### ISSUE TITLE
Add tests? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#7]
As we copy the notebooks is it possible to execute those during the testing of the containers? By using different stages for building the image and testing the images we could even run all the tests in parallel - the pyiron CI script uses such stages to test on multiple operation systems and then build the documentation only when the tests were successful https://github.com/pyiron/pyiron/blob/master/.travis.yml#L3

**Comment by muh-hassani** [comment]
If I understand well, in [https://github.com/pyiron/pyiron/blob/master/.travis.yml#L3](https://github.com/pyiron/pyiron/blob/master/.travis.yml#L3), you create a linux environment for your test, but in this case, we should run a docker container from the images and run the tests within the image. I will read about how we can do it.

**Comment by jan-janssen** [comment]
To execute the notebooks inside a docker container please use: `jupyter nbconvert` like we do it in the script job:
https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/job/script.py#L265

**Comment by muh-hassani** [comment]
@jan-janssen Your pace is high, even at the weekend. Thanks for your changes.

**Comment by muh-hassani** [comment]
@jan-janssen if you see in the build log [here](https://travis-ci.com/github/pyiron/docker-stacks/builds/190783775) in line 1418, although the test was not successful the command exited with 0.
It is since docker run command ran successfully, but the bash command inside the docker was not successful. I know that later builds did not have this issue, but in case in future, some notebooks have a problem and were not executed correctly, this test would not be effective.
